# Generated by Django 4.0.5 on 2022-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
